# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "si"
displayName: "si"
description: "Smart Intersection Deployment Package"
version: "0.2.0"

applications:
  - name: si-app
    version: 0.2.0

defaultNamespaces:
  si-app: si

deploymentProfiles:
  - name: "default"
    description: "Uses CPU for inferencing"
    applicationProfiles:
      - application: "si-app"
        profile: "default"
