# Copyright Intel Corporation

namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: IfNotPresent
storageClassName: manual
num_video_instances: 1
env:
  ENABLE_WEBRTC: "true"
  ENABLE_RTSP: "true"
  HOST_IP: localhost
  REST_SERVER_PORT: 30107
  RTSP_CAMERA_IP: 
  ENABLE_HTTPS_MODE: false
  MIN_LOG_LEVEL: DEBUG
  MINIO_ACCESS_KEY:
  MINIO_BUCKET_NAME: model-registry
  MINIO_HOSTNAME: mraas-minio
  MINIO_SECRET_KEY:
  MINIO_SERVER_PORT: "8000"
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:8000
  SERVER_PORT: "8111"
  https_proxy:
  http_proxy:
  no_proxy: mraas-minio
  NO_PROXY: mraas-minio
  POSTGRES_USER: postgres
  POSTGRES_DB: model_registry_db
  POSTGRES_PASSWORD:
  S3_STORAGE_PORT: 30800
  ENABLE_OPEN_TELEMETRY: true
  OTEL_EXPORT_INTERVAL_MILLIS: 5000
  OPCUA_SERVER_IP:
  OPCUA_SERVER_PORT:
  OPCUA_SERVER_USERNAME:
  OPCUA_SERVER_PASSWORD:
  MR_URL: https://<HOST_IP>:30443/registry/
  MR_SAVED_MODELS_DIR: ./mr_models
  MR_REQUEST_TIMEOUT: 300
  MR_VERIFY_CERT:
  SAMPLE_APP: weld-porosity
privileged_access_required: false
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
webrtcturnserver:
  username:
  password:
images:
  minio: minio/minio:RELEASE.2020-12-12T08-39-07Z
  model_registry: intel/model-registry:1.0.3
  dlstreamer_pipeline_server: intel/dlstreamer-pipeline-server:2025.2-ubuntu22-rc1
  nginx: nginx:1.27-alpine
  mqtt_broker: eclipse-mosquitto:latest
config:
  prometheus:
    name: prometheus
    int:
      prometheus_port: "9090"
  otel_collector:
    name: otel-collector
    int:
      otlp_grpc_port: "4317"
      otlp_http_port: "4318"
      otlp_prometheus_endpoint_port: "9464"
  mediamtx:
    name: mediamtx
    int:
      mediamtx_port: "8889"
      mediamtx_sdp_port: "8189"
      mediamtx_api_port: "9997"
  coturn:
    name: coturn
    int:
      coturn_tcp_port: "3478"
      coturn_udp_port: "3478"
    ext:
      coturn_tcp_port: "30478"
      coturn_udp_port: "30478"
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
  model_registry:
    name: model-registry
    int:
      port: "8111"
  nginx:
    name: nginx-reverse-proxy
    int:
      http_port: "80"
      https_port: "443"
    ext:
      http_port: "30080"
      https_port: "30443"
  mqtt_broker:
    name: mqtt-broker
    int:
      mqtt_port: "1883"
volumes:
  pipelines:
    name: vol-pipelines
    size: 100Mi
    location: "/home/pipeline-server/pipelines"
    hostpath: "/opt/intel/eii/pipelines"
  models:
    name: vol-models
    size: 500Mi
    location: "/home/pipeline-server/models"
    hostpath: "/opt/intel/eii/models"
