global:
  # pvcName is the name of common PVC used by multiple microservices for persisting models, cache and other files.
  pvcName: "smart-nvr-pvc"
  # claimSize is the size of the PVC to be created.
  claimSize: "50Gi"  
  # keepPvc should be set to true to retain the PVC after uninstalling the chart.
  keepPvc: false
  storageClassName: 

  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  env:
    FRIGATE_MQTT_USER: ""
    FRIGATE_MQTT_PASSWORD: ""

frigate:
  env:
    OPENAI_BASE_URL: ""
    OPENAI_API_KEY: ""

nvr-event-router:
  env:
    VSS_SEARCH_IP: ""
    VSS_SEARCH_PORT: 
    VSS_SUMMARY_IP: ""
    VSS_SUMMARY_PORT: 

nvr-event-router-ui:
  env:
    NVR_GENAI: ""

