apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvr-event-router-ui
  labels:
    app: nvr-event-router-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nvr-event-router-ui
  template:
    metadata:
      labels:
        app: nvr-event-router-ui
    spec:
      initContainers:
        - name: wait-for-nvr-event-router
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z nvr-event-router 8000; do echo waiting for nvr-event-router; sleep 2; done;']

      containers:
        - name: nvr-event-router-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 7860
          env:
            - name: MODE
              value: "{{ .Values.env.MODE }}"
            - name: API_BASE_URL
              value: "{{ .Values.env.API_BASE_URL }}"
            - name: EVENT_POLL_INTERVAL
              value: "{{ .Values.env.EVENT_POLL_INTERVAL }}"
            - name: NVR_GENAI
              value: "{{ .Values.env.NVR_GENAI }}"
            - name: no_proxy
              value: "{{ .Values.global.proxy.no_proxy }},{{ .Values.env.VSS_SEARCH_IP }},{{ .Values.env.VSS_SUMMARY_IP }}"
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
              readOnly: {{ .Values.volume.readOnly }}

      volumes:
        - name: {{ .Values.volume.name }}
          hostPath:
            path: {{ .Values.volume.hostPath }}

