apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "nvr-event-router-ui" }}
  labels:
    app: nvr-event-router-ui
spec:
  selector:
    app: nvr-event-router-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type | default "ClusterIP" }}
