mqtt:
  enabled: true
  host: mqtt-broker
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

genai:
  enabled: false
  provider: openai
  model: Qwen/Qwen2.5-VL-3B-Instruct

logger:
  default: info


semantic_search:
  enabled: true
  reindex: false

record:
  enabled: true
  retain:
    days: 7
    mode: all

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:8554/camera1
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -r 5
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -profile:v baseline -level 3.1 -crf 23 -g 50 -pix_fmt yuv420p -movflags +faststart
    detect:
      enabled: false
      max_disappeared: 30
      width: 1280
      height: 720
      fps: 10
    objects:
      track: [vehicle,pedestrian]
      filters:
        car:
          min_score: 0.6
          threshold: 0.70
    record:
      enabled: true
      retain:
        days: 1
    snapshots:
      enabled: true
      retain:
        default: 1
    genai:
      enabled: false
      use_snapshot: true
      objects:
        - vehicle
        - pedestrian
        - car
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:8554/camera2
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -r 5
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -profile:v baseline -level 3.1 -crf 23 -g 50 -pix_fmt yuv420p -movflags +faststart
    detect:
      enabled: false
      max_disappeared: 30
      width: 1280
      height: 720
      fps: 10
    objects:
      track: [vehicle,pedestrian]
      filters:
        car:
          min_score: 0.6
          threshold: 0.70
    record:
      enabled: true
      retain:
        days: 1
    snapshots:
      enabled: true
      retain:
        default: 1
    genai:
      enabled: false
      use_snapshot: true
      objects:
        - vehicle
        - pedestrian
        - car
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:8554/camera3
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -r 5
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -profile:v baseline -level 3.1 -crf 23 -g 50 -pix_fmt yuv420p -movflags +faststart
    detect:
      enabled: false
      max_disappeared: 30
      width: 1280
      height: 720
      fps: 10
    objects:
      track: [vehicle,pedestrian]
      filters:
        car:
          min_score: 0.6
          threshold: 0.70
    record:
      enabled: true
      retain:
        days: 1
    snapshots:
      enabled: true
      retain:
        default: 1
    genai:
      enabled: false
      use_snapshot: true
      objects:
        - vehicle
        - pedestrian
        - car
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:8554/camera4
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -r 5
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -profile:v baseline -level 3.1 -crf 23 -g 50 -pix_fmt yuv420p -movflags +faststart
    detect:
      enabled: false
      max_disappeared: 30
      width: 1280
      height: 720
      fps: 10
    objects:
      track: [vehicle,pedestrian]
      filters:
        car:
          min_score: 0.6
          threshold: 0.70
    record:
      enabled: true
      retain:
        days: 1
    snapshots:
      enabled: true
      retain:
        default: 1
    genai:
      enabled: false
      use_snapshot: true
      objects:
        - vehicle
        - pedestrian
        - car                
version: 0.15-1