# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "wp"
displayName: "wp"
description: "Weld Porosity Deployment Package"
version: "1.3.0"

applications:
  - name: wp-app
    version: 1.3.0

defaultNamespaces:
  wp-app: wp

deploymentProfiles:
  - name: "default"
    description: "Uses CPU for inferencing"
    applicationProfiles:
      - application: "wp-app"
        profile: "default"
  - name: "with-intel-gpu"
    description: "Uses Intel GPU for inferencing, needs Intel GPU extension"
    applicationProfiles:
      - application: "wp-app"
        profile: "with-intel-gpu"