services:
  milvus-db:
    image: docker.io/milvusdb/milvus:v2.5.15
    container_name: ibvs-milvusdb
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=
      - http_proxy=
      - https_proxy=
      - no_proxy=
    volumes:
      - milvus-data:/var/lib/milvus
      - ./src/milvus-db/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./src/milvus-db/user.yaml:/milvus/configs/user.yaml
      # This port conflicts with etcd when exposed, so it is commented out:
      # - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    command: ["milvus", "run", "standalone"]
    restart: on-failure:5
  milvus-ui:
    image: docker.io/zilliz/attu:v2.4
    container_name: ibvs-milvusui
    environment:
      - MILVUS_URL=milvus-db:19530
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=
      - http_proxy=
      - https_proxy=
      - no_proxy=
    restart: on-failure:5
    depends_on:
      milvus-db:
        condition: service_healthy

  feature-matching:
    image: ${DOCKER_REGISTRY}intel/feature-matching:v1.1.0-RC1
    container_name: ibvs-featurematching
    build:
      context: src/feature-matching
      dockerfile: Dockerfile
    read_only: true
    tmpfs:
    - /usr/src/app/static:uid=1999,gid=1999,mode=775
    environment:
      MILVUS_ENDPOINT: http://milvus-db:19530
      COLLECTION_NAME: my_image_collection
      MODEL_DIM: 1000
      MQTT_BROKER: ibvs-broker
      MQTT_PORT: 1883
      MQTT_TOPIC: edge_video_analytics_results
      CONFIDENCE_THRESHOLD: 0.4
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      NO_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
    depends_on:
      milvus-db:
        condition: service_healthy
      broker:
        condition: service_started
    volumes:
      - image-data:/user/src/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure:5
  streaming-pipeline:
    image: ${DOCKER_REGISTRY}intel/streaming-pipeline:v1.1.0-RC1
    build:
      context: src/streaming-pipeline
      dockerfile: Dockerfile
    container_name: ibvs-streaming
    environment:
      https_proxy: "${https_proxy}"
      http_proxy: "${http_proxy}"
      no_proxy: "${no_proxy}"
    command: >
      bash -c "
        wget -O file.mp4 https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4 && \
        unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY && \
        gst-launch-1.0 filesrc location=file.mp4 ! qtdemux name=mdemux ! h264parse ! video/x-h264,stream-format=byte-stream ! mpegtsmux name=mux ! filesink location=file.ts && \
        gst-launch-1.0 multifilesrc location=file.ts loop=true ! tsdemux ! h264parse ! rtspclientsink protocols=tcp location=rtsp://rtsp-server:8554/stream
      "
    depends_on:
      rtsp-server:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "ffprobe -v error -rtsp_transport tcp rtsp://ibvs-mediamtx:8554/stream -show_streams || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure:5
  rtsp-server:
    image: docker.io/bluenviron/mediamtx:1.10.0
    container_name: ibvs-mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=127.0.0.1
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=
      - http_proxy=
      - https_proxy=
      - no_proxy=
    restart: on-failure:5
  broker:
    image: docker.io/library/eclipse-mosquitto:2.0.20
    container_name: ibvs-broker
    volumes:
      - ./src/broker:/mosquitto/config
    restart: unless-stopped
    healthcheck:
      test:  ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
  dlstreamer-pipeline-server:
    image: ${DLSTREAMER_PIPELINE_SERVER_IMAGE}
    hostname: dlstreamer-pipeline-server
    container_name: ibvs-dlstreamer-pipeline-server
    read_only: true
    security_opt:
      - no-new-privileges
    privileged: false
    tty: true
    entrypoint: ["./run.sh"]
      # - '8554:8554'
    environment:
      - ENABLE_RTSP=true
      - RTSP_PORT=8554
      - ENABLE_WEBRTC=true
      - WEBRTC_SIGNALING_SERVER=ws://localhost:8443
      - RUN_MODE=EVA
      - GENICAM=Balluff
      - GST_DEBUG="1,gencamsrc:2"
      # Default Detection and Classification Device
      - DETECTION_DEVICE=CPU
      - CLASSIFICATION_DEVICE=CPU
      - ADD_UTCTIME_TO_METADATA=true
      - LSFEATURE_NAME="dlstreamer-pipeline-server"
      # - RUNTIME_LICENSE_CHECK_FREQ_SECS=${RUNTIME_LICENSE_CHECK_FREQ_SECS}
      # - APPLICATION_RESTART_FREQ_SECS=${APPLICATION_RESTART_FREQ_SECS}
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - MTLS_VERIFICATION=false # if HTTPS=true, enable/disable client certificate verification for mTLS
      # Model Registry Microservice
      # - MR_VERIFY_CERT=${MR_VERIFY_CERT}
      # - MR_USER_PASSWORD=${MR_USER_PASSWORD}
      # Append pipeline name to a publisher topic
      - APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC=false
      - REST_SERVER_PORT=8080
      - MQTT_HOST=ibvs-broker
      - MQTT_PORT=1883
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=
      - http_proxy=
      - https_proxy=
      - no_proxy=
    volumes:
      - "./src/dlstreamer-pipeline-server/configs/filter-pipeline/config.cpu.json:/home/pipeline-server/config.json"
      # - "./src/dlstreamer-pipeline-server/configs/filter-pipeline/config.gpu.json:/home/pipeline-server/config.json"
      - "dlstreamer-pipeline-server-pipeline-root:/var/cache/pipeline_root:uid=1999,gid=1999"
      # - "../certificates:/MqttCerts:ro"
      # - "../Certificates/ssl_server/:/run/secrets/EdgeVideoAnalyticsMicroservice_Server:ro"
      # - "../Certificates/model_registry/:/run/secrets/ModelRegistry_Server:ro"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - dlstreamer-pipeline-server-tmp:/tmp
      # - "../mr_models:/home/pipeline-server/mr_models:rw"
      - "./src/dlstreamer-pipeline-server/models/person-vehicle-bike-detection-2004:/models/person-vehicle-bike-detection-2004"
      - "./src/dlstreamer-pipeline-server/models/resnet-50-pytorch:/models/resnet50"
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 209:* rmw'
      - 'a 189:* rwm'
    devices:
      - "/dev:/dev"
    depends_on:
      broker:
        condition: service_started
    restart: on-failure:5
  app:
    image: ${DOCKER_REGISTRY}intel/image-based-video-search:v1.1.0-RC1
    container_name: ibvs-app
    build:
      context: src/app
      dockerfile: Dockerfile
    read_only: true
    depends_on:
      streaming-pipeline:
        condition: service_healthy
      feature-matching:
        condition: service_healthy
      dlstreamer-pipeline-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: on-failure:5
  nginx:
    image: nginx:1.27-alpine
    container_name: ibvs-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8554:8554"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/generate_certs.sh:/usr/local/bin/generate_certs.sh:ro
    entrypoint: ["/usr/local/bin/generate_certs.sh"]
    depends_on:
      - app
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy=
      - NO_PROXY=
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  milvus-data:
  image-data:
  dlstreamer-pipeline-server-pipeline-root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  dlstreamer-pipeline-server-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
