apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vlmOpenvinoServing.fullname" . }}
  labels:
    app: {{ include "vlmOpenvinoServing.name" . }}
spec:
  replicas: {{ .Values.vlmOpenvinoServing.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.vlmOpenvinoServing.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vlmOpenvinoServing.name }}
    spec:
      hostIPC: true
      securityContext:
        fsGroup: {{ .Values.vlmOpenvinoServing.videoGroupId }}
      containers:
        - name: {{ .Values.vlmOpenvinoServing.name }}
          image: "{{ if .Values.global.registry }}{{ .Values.global.registry }}{{ end }}{{ .Values.vlmOpenvinoServing.image.repository }}:{{ .Values.vlmOpenvinoServing.image.tag }}"
          imagePullPolicy: {{ .Values.vlmOpenvinoServing.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.vlmOpenvinoServing.service.targetPort }}
          env:
            - name: VLM_MODEL_NAME
              value: {{ required "Value for `global.VLM_MODEL_NAME` is required!" .Values.global.VLM_MODEL_NAME | quote }}
            - name: VLM_COMPRESSION_WEIGHT_FORMAT
              value: {{ .Values.vlmOpenvinoServing.env.VLM_COMPRESSION_WEIGHT_FORMAT | quote }}
            - name: VLM_DEVICE
              value: {{ .Values.vlmOpenvinoServing.env.VLM_DEVICE | quote }}
            - name: VLM_SEED
              value: {{ .Values.vlmOpenvinoServing.env.VLM_SEED | quote }}
            - name: http_proxy
              value: {{ .Values.global.proxy.http_proxy | quote }}
            - name: https_proxy
              value: {{ .Values.global.proxy.https_proxy | quote }}
            - name: no_proxy
              value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,.svc.cluster.local"
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,.svc.cluster.local"
            - name: no_proxy_env
              value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,.svc.cluster.local"
            - name: HF_ENDPOINT
              value: {{ .Values.vlmOpenvinoServing.env.HF_ENDPOINT | quote }}
          volumeMounts:
          - name: workspace
            mountPath: /app/ov_models
          - name: workspace
            mountPath: /home/appuser/.cache/huggingface
          - name: gpu-devices
            mountPath: /dev/dri
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ .Values.global.sharedPvcName }}
        - name: gpu-devices
          hostPath:
            path: /dev/dri
            type: Directory