apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visualSearchQaApp.fullname" . }}
  labels:
    app: {{ include "visualSearchQaApp.name" . }}
spec:
  replicas: {{ .Values.visualSearchQaApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.visualSearchQaApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.visualSearchQaApp.name }}
    spec:
      hostIPC: true
      containers:
      - name: {{ .Values.visualSearchQaApp.name }}
        image: "{{ if .Values.global.registry }}{{ .Values.global.registry }}{{ end }}{{ .Values.visualSearchQaApp.image.repository }}:{{ .Values.visualSearchQaApp.image.tag }}"
        imagePullPolicy: {{ .Values.visualSearchQaApp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.servicePorts.visualSearch }}
        env:
        - name: EMBEDDING_MODEL_NAME
          value: {{ required "Value for `global.EMBEDDING_MODEL_NAME` is required!" .Values.global.EMBEDDING_MODEL_NAME | quote }}
        - name: EMBEDDING_BASE_URL
          value: {{ .Values.multimodalembeddingServing.env.EMBEDDING_BASE_URL | quote }}
        - name: VLM_MODEL_NAME
          value: {{ required "Value for `global.VLM_MODEL_NAME` is required!" .Values.global.VLM_MODEL_NAME | quote }}
        - name: DEVICE
          value: {{ .Values.visualSearchQaApp.env.DEVICE | quote }}
        - name: no_proxy
          value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,.svc.cluster.local"
        - name: http_proxy
          value: {{ .Values.global.proxy.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.global.proxy.https_proxy | quote }}
        - name: DATA_INGEST_WITH_DETECT
          value: {{ .Values.visualSearchQaApp.env.DATA_INGEST_WITH_DETECT | quote }}
        - name: VISUAL_SEARCH_QA_UI_PORT
          value: {{ .Values.visualSearchQaApp.env.VISUAL_SEARCH_QA_UI_PORT | quote }}
        - name: MAX_MAX_NUM_SEARCH_RESULTS
          value: {{ .Values.visualSearchQaApp.env.MAX_MAX_NUM_SEARCH_RESULTS | quote }}
        - name: DEFAULT_NUM_SEARCH_RESULTS
          value: {{ .Values.visualSearchQaApp.env.DEFAULT_NUM_SEARCH_RESULTS | quote }}
        - name: SHOW_RESULT_PER_ROW
          value: {{ .Values.visualSearchQaApp.env.SHOW_RESULT_PER_ROW | quote }}
        - name: BACKEND_VQA_BASE_URL
          value: {{ .Values.visualSearchQaApp.env.BACKEND_VQA_BASE_URL | quote }}
        - name: BACKEND_SEARCH_BASE_URL
          value: {{ .Values.visualSearchQaApp.env.BACKEND_SEARCH_BASE_URL | quote }}
        - name: BACKEND_DATAPREP_BASE_URL 
          value: {{ .Values.visualSearchQaApp.env.BACKEND_DATAPREP_BASE_URL | quote }}
        - name: HOST_DATA_PATH
          value: {{ .Values.volumes.hostDataPath.hostPath | quote }}
        - name: host_ip
          value: visual-search-qa-app.vsqa.svc.cluster.local
        volumeMounts:
        - name: data
          mountPath: /home/user/data
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.volumes.hostDataPath.hostPath }}


