apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retrieverMilvus.fullname" . }}
  labels:
    app: {{ include "retrieverMilvus.name" . }}
spec:
  replicas: {{ .Values.retrieverMilvus.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.retrieverMilvus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.retrieverMilvus.name }}
    spec:
      hostIPC: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: {{ .Values.retrieverMilvus.name }}
        image: "{{ if .Values.global.registry }}{{ .Values.global.registry }}{{ end }}{{ .Values.retrieverMilvus.image.repository }}:{{ .Values.retrieverMilvus.image.tag }}"
        imagePullPolicy: {{ .Values.retrieverMilvus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.servicePorts.retriever }}
        env:
        - name: MILVUS_HOST
          value: {{ .Values.MILVUS_HOST | quote }}
        - name: MILVUS_PORT
          value: {{ .Values.MILVUS_PORT | quote  }}
        - name: EMBEDDING_MODEL_NAME
          value: {{ required "Value for `global.EMBEDDING_MODEL_NAME` is required!" .Values.global.EMBEDDING_MODEL_NAME | quote }}
        - name: EMBEDDING_BASE_URL
          value: {{ .Values.multimodalembeddingServing.env.EMBEDDING_BASE_URL | quote }}
        - name: HF_ENDPOINT
          value: {{ .Values.retrieverMilvus.env.HF_ENDPOINT | quote }}
        - name: no_proxy
          value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,.svc.cluster.local"
        - name: http_proxy
          value: {{ .Values.global.proxy.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.global.proxy.https_proxy | quote }}
        livenessProbe:
          httpGet:
            path: /v1/retrieval/health
            port: {{ .Values.servicePorts.retriever }}
          {{- with .Values.retrieverMilvus.livenessProbe }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        readinessProbe:
          {{- if .Values.retrieverMilvus.readinessProbe.sameAsLiveness }}
          httpGet:
            path: /v1/retrieval/health
            port: {{ .Values.servicePorts.retriever }}
          initialDelaySeconds: {{ .Values.retrieverMilvus.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.retrieverMilvus.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.retrieverMilvus.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.retrieverMilvus.livenessProbe.failureThreshold }}
          {{- end }}

