apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-recordings-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.keepPvc }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.claimSize }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
