# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      rebuild-all:
        description: 'Whether to force rebuild all components'
        type: boolean
        default: false
        required: false

permissions:
  contents: read

jobs:
  check-changes:
    name: "Checking for changes"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      fast-mapping-changed: ${{ steps.filter.outputs.fast-mapping-location || inputs.rebuild-all }}
      its-planner-changed: ${{ steps.filter.outputs.its-planner-location || inputs.rebuild-all }}
      multicam-demo-changed: ${{ steps.filter.outputs.multicam-demo-location || inputs.rebuild-all }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
          sparse-checkout: robotics-ai-suite/components
      - name: Configure paths to look for changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: |
            fast-mapping-location:
              - 'robotics-ai-suite/components/fast-mapping/**'
            its-planner-location:
              - 'robotics-ai-suite/components/its-planner/**'
            multicam-demo-location:
              - 'robotics-ai-suite/components/multicam-demo/**'

  fast-mapping:
    name: "Fast Mapping"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.fast-mapping-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-fast-mapping.yaml"

  its-planner:
    name: "ITS Planner"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.its-planner-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-its-planner.yaml"

  multicam-demo:
    name: "Multi-Camera Demo"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.multicam-demo-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-multicam-demo.yaml"
